// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package encap

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfFlowKeyV4 struct {
	_       structs.HostLayout
	Ifindex uint32
	Saddr   uint32
	Daddr   uint32
	Sport   uint16
	Dport   uint16
	Proto   uint8
	Pad     [3]uint8
}

type bpfFlowKeyV6 struct {
	_       structs.HostLayout
	Ifindex uint32
	Saddr   [16]uint8
	Daddr   [16]uint8
	Sport   uint16
	Dport   uint16
	Proto   uint8
	Pad     [3]uint8
}

type bpfMetricKey struct {
	_       structs.HostLayout
	Ifindex uint32
	Counter uint32
}

type bpfOuterHdrCache struct {
	_   structs.HostLayout
	Len uint16
	Hdr [96]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapFlowStateV4   = "flow_state_v4"
	bpfMapFlowStateV6   = "flow_state_v6"
	bpfMapMetrics       = "metrics"
	bpfProgEncap        = "encap"
	bpfVarEniMode       = "eni_mode"
	bpfVarIpv4Enabled   = "ipv4_enabled"
	bpfVarIpv6Enabled   = "ipv6_enabled"
	bpfVarUplinkIfindex = "uplink_ifindex"
	bpfVarUplinkMac0    = "uplink_mac_0"
	bpfVarUplinkMac1    = "uplink_mac_1"
	bpfVarUplinkMac2    = "uplink_mac_2"
	bpfVarUplinkMac3    = "uplink_mac_3"
	bpfVarUplinkMac4    = "uplink_mac_4"
	bpfVarUplinkMac5    = "uplink_mac_5"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	Encap *ebpf.ProgramSpec `ebpf:"encap"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	FlowStateV4 *ebpf.MapSpec `ebpf:"flow_state_v4"`
	FlowStateV6 *ebpf.MapSpec `ebpf:"flow_state_v6"`
	Metrics     *ebpf.MapSpec `ebpf:"metrics"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	EniMode       *ebpf.VariableSpec `ebpf:"eni_mode"`
	Ipv4Enabled   *ebpf.VariableSpec `ebpf:"ipv4_enabled"`
	Ipv6Enabled   *ebpf.VariableSpec `ebpf:"ipv6_enabled"`
	UplinkIfindex *ebpf.VariableSpec `ebpf:"uplink_ifindex"`
	UplinkMac0    *ebpf.VariableSpec `ebpf:"uplink_mac_0"`
	UplinkMac1    *ebpf.VariableSpec `ebpf:"uplink_mac_1"`
	UplinkMac2    *ebpf.VariableSpec `ebpf:"uplink_mac_2"`
	UplinkMac3    *ebpf.VariableSpec `ebpf:"uplink_mac_3"`
	UplinkMac4    *ebpf.VariableSpec `ebpf:"uplink_mac_4"`
	UplinkMac5    *ebpf.VariableSpec `ebpf:"uplink_mac_5"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	FlowStateV4 *ebpf.Map `ebpf:"flow_state_v4"`
	FlowStateV6 *ebpf.Map `ebpf:"flow_state_v6"`
	Metrics     *ebpf.Map `ebpf:"metrics"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.FlowStateV4,
		m.FlowStateV6,
		m.Metrics,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	EniMode       *ebpf.Variable `ebpf:"eni_mode"`
	Ipv4Enabled   *ebpf.Variable `ebpf:"ipv4_enabled"`
	Ipv6Enabled   *ebpf.Variable `ebpf:"ipv6_enabled"`
	UplinkIfindex *ebpf.Variable `ebpf:"uplink_ifindex"`
	UplinkMac0    *ebpf.Variable `ebpf:"uplink_mac_0"`
	UplinkMac1    *ebpf.Variable `ebpf:"uplink_mac_1"`
	UplinkMac2    *ebpf.Variable `ebpf:"uplink_mac_2"`
	UplinkMac3    *ebpf.Variable `ebpf:"uplink_mac_3"`
	UplinkMac4    *ebpf.Variable `ebpf:"uplink_mac_4"`
	UplinkMac5    *ebpf.Variable `ebpf:"uplink_mac_5"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	Encap *ebpf.Program `ebpf:"encap"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.Encap,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
