// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package encap

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfFlowKey struct {
	_       structs.HostLayout
	Ifindex uint32
	Saddr   struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	Daddr struct {
		_  structs.HostLayout
		V4 uint32
		_  [12]byte
	}
	Sport uint16
	Dport uint16
	Proto uint8
	IsV6  uint8
	Pad   [2]uint8
}

type bpfMetricKey struct {
	_       structs.HostLayout
	Ifindex uint32
	Counter uint32
}

type bpfOuterHdrCache struct {
	_   structs.HostLayout
	Hdr [82]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapFlowState     = "flow_state"
	bpfMapMetrics       = "metrics"
	bpfProgEncap        = "encap"
	bpfVarEniMode       = "eni_mode"
	bpfVarIpv4Enabled   = "ipv4_enabled"
	bpfVarIpv6Enabled   = "ipv6_enabled"
	bpfVarUplinkIfindex = "uplink_ifindex"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	Encap *ebpf.ProgramSpec `ebpf:"encap"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	FlowState *ebpf.MapSpec `ebpf:"flow_state"`
	Metrics   *ebpf.MapSpec `ebpf:"metrics"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	EniMode       *ebpf.VariableSpec `ebpf:"eni_mode"`
	Ipv4Enabled   *ebpf.VariableSpec `ebpf:"ipv4_enabled"`
	Ipv6Enabled   *ebpf.VariableSpec `ebpf:"ipv6_enabled"`
	UplinkIfindex *ebpf.VariableSpec `ebpf:"uplink_ifindex"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	FlowState *ebpf.Map `ebpf:"flow_state"`
	Metrics   *ebpf.Map `ebpf:"metrics"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.FlowState,
		m.Metrics,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	EniMode       *ebpf.Variable `ebpf:"eni_mode"`
	Ipv4Enabled   *ebpf.Variable `ebpf:"ipv4_enabled"`
	Ipv6Enabled   *ebpf.Variable `ebpf:"ipv6_enabled"`
	UplinkIfindex *ebpf.Variable `ebpf:"uplink_ifindex"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	Encap *ebpf.Program `ebpf:"encap"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.Encap,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
